version: "3"
services:
  api-gateway:
    build: ./api-gateway
    command: yarn start:dev
    env_file:
      - .env
      - ./api-gateway/gateway.env
    depends_on:
      - rabbitmq
      - user
      - token
      - mailer
      - permission
      - group
    ports:
      - "7000:7000"
    volumes:
      - ./api-gateway:/usr/app
      - /usr/app/node_modules
    networks:
      - backend

  # USER SERVICE CONFIGURATION
  user:
    build: ./user
    command: yarn start:dev
    depends_on:
      - rabbitmq
      - mailer
      - user-db
    links:
      - rabbitmq
    env_file:
      - .env
      - ./user/user.env
    ports:
      - "7100:7100"
    volumes:
      - ./user:/usr/app
      - /usr/app/node_modules
    networks:
      - backend
  # POSTGRES DB
  user-db:
    container_name: user-postgres
    volumes:
      - /data/user-postgres:/data/postgres
    env_file:
      - ./user/user.env
    image: postgres:alpine
    ports:
      - "7200:5432"
    networks:
      - backend
      - user-postgres

  # TOKEN SERVICE CONFIGURATION
  token:
    build: ./token
    command: yarn start:dev
    depends_on:
      - rabbitmq
      - token-db
    links:
      - rabbitmq
    env_file:
      - .env
      - ./token/user-token.env
    ports:
      - "7101:7101"
    volumes:
      - ./token:/usr/app
      - /usr/app/node_modules
    networks:
      - backend
  # POSTGRES DB
  token-db:
    container_name: token-postgres
    volumes:
      - /data/token-postgres:/data/postgres
    env_file:
      - ./token/user-token.env
    image: postgres:alpine
    ports:
      - "7201:5432"
    networks:
      - token-postgres
      - backend

# PERMISSION SERVICE CONFIGURATION
  permission:
    build: ./permission
    command: yarn start:dev
    depends_on:
      - rabbitmq
      - permission-db
    links:
      - rabbitmq
    env_file:
      - .env
      - ./permission/permission.env
    ports:
      - "7102:7102"
    volumes:
      - ./permission:/usr/app
      - /usr/app/node_modules
    networks:
      - backend
  # POSTGRES DB
  permission-db:
    container_name: permission-postgres
    volumes:
      - /data/permission-postgres:/data/postgres
    env_file:
      - ./permission/permission.env
    image: postgres:alpine
    ports:
      - "7202:5432"
    networks:
      - permission-postgres
      - backend

# GROUP SERVICE CONFIGURATION
  group:
    build: ./group
    command: yarn start:dev
    depends_on:
      - rabbitmq
      - group-db
    links:
      - rabbitmq
    env_file:
      - .env
      - ./group/group.env
    ports:
      - "7105:7105"
    volumes:
      - ./group:/usr/app
      - /usr/app/node_modules
    networks:
      - backend
  # POSTGRES DB
  group-db:
    container_name: group-postgres
    volumes:
      - /data/group-postgres:/data/postgres
    env_file:
      - ./group/group.env
    image: postgres:alpine
    ports:
      - "7205:5432"
    networks:
      - group-postgres
      - backend

# MAILER SERVICE CONFIGURATION
  mailer:
    build: ./mailer
    command: yarn start:dev
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    env_file:
      - .env
      - ./mailer/mailer.env
    ports:
      - "7120:7120"
    volumes:
      - ./mailer:/usr/app
      - /usr/app/node_modules
    networks:
      - backend

#RABBITMQ CONFIGURATION
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    networks:
      - backend

  # NETWORKS
networks:
  backend:
  user-postgres:
    driver: bridge
  token-postgres:
    driver: bridge
  permission-postgres:
    driver: bridge
  group-postgres:
    driver: bridge