export const USER_SERVICE = 'USER_SERVICE';
export const GROUP_SERVICE = 'GROUP_SERVICE';
export const SECTION_SERVICE = 'USER_SERVICE';
export const TOKEN_SERVICE = 'TOKEN_SERVICE';
export const PERMISSION_SERVICE = 'PERMISSION_SERVICE';
export const MAILER_SERVICE = 'MAILER_SERVICE';
